In [13]:
import csv
import numpy as np
from prettytable import PrettyTable
import math
import statistics as stats

In [14]:
with open ('africa_pop_data.csv', 'r') as csv_file:
    csvreader = csv.reader(csv_file)
    countrydata = []
    for line in csvreader:
        countrydata.append(line)
    print(countrydata)

[['Country', 'Code', '2015', '2016', '2017', '2018', '2019'], ['Algeria', 'DZA', '39728025', '40551404', '41389198', '42228429', '43053054'], ['Angola', 'AGO', '27884381', '28842484', '29816748', '30809762', '31825295'], ['Benin', 'BEN', '10575952', '10872067', '11175204', '11485048', '11801151'], ['Botswana', 'BWA', '2120716', '2159944', '2205128', '2254126', '2303697'], ['Burkina Faso', 'BFA', '18110624', '18646378', '19193284', '19751535', '20321378'], ['Cabo Verde', 'CPV', '524743', '531146', '537497', '543767', '549935'], ['Cameroon', 'CMR', '23298368', '23926539', '24566045', '25216237', '25876380'], ['Central African Republic', 'CAF', '4493170', '4537687', '4596028', '4666377', '4745185'], ['Chad', 'TCD', '14110975', '14561666', '15016773', '15477751', '15946876'], ['Comoros', 'COM', '777424', '795592', '813892', '832322', '850886'], ['Congo, Dem. Rep.', 'COD', '76244544', '78789127', '81398764', '84068091', '86790567'], ['Congo, Rep.', 'COG', '4856095', '4980999', '5110702', '5

In [68]:
arraydata = np.array(countrydata)
numdata = arraydata[:, 2:7]
print(numdata)

[['2015' '2016' '2017' '2018' '2019']
 ['39728025' '40551404' '41389198' '42228429' '43053054']
 ['27884381' '28842484' '29816748' '30809762' '31825295']
 ['10575952' '10872067' '11175204' '11485048' '11801151']
 ['2120716' '2159944' '2205128' '2254126' '2303697']
 ['18110624' '18646378' '19193284' '19751535' '20321378']
 ['524743' '531146' '537497' '543767' '549935']
 ['23298368' '23926539' '24566045' '25216237' '25876380']
 ['4493170' '4537687' '4596028' '4666377' '4745185']
 ['14110975' '14561666' '15016773' '15477751' '15946876']
 ['777424' '795592' '813892' '832322' '850886']
 ['76244544' '78789127' '81398764' '84068091' '86790567']
 ['4856095' '4980999' '5110702' '5244363' '5380508']
 ['23226143' '23822714' '24437469' '25069229' '25716544']
 ['913993' '929112' '944097' '958920' '973560']
 ['92442547' '94447072' '96442593' '98423595' '100388073']
 ['1168568' '1215179' '1262001' '1308974' '1355986']
 ['1104044' '1113984' '1124753' '1136191' '1148130']
 ['100835458' '103603501' '106

In [16]:
list(countrydata)
header = arraydata[0, :]
#lheader = header.tolist()
statdata = np.delete(arraydata, 0, 0)
table = PrettyTable()
table.field_names = header
for x in range (0,51):
    y = statdata [x, :].tolist()
    table.add_row(y)
table.align = "r"
print (table)

+--------------------------+------+-----------+-----------+-----------+-----------+-----------+
|                  Country | Code |      2015 |      2016 |      2017 |      2018 |      2019 |
+--------------------------+------+-----------+-----------+-----------+-----------+-----------+
|                  Algeria |  DZA |  39728025 |  40551404 |  41389198 |  42228429 |  43053054 |
|                   Angola |  AGO |  27884381 |  28842484 |  29816748 |  30809762 |  31825295 |
|                    Benin |  BEN |  10575952 |  10872067 |  11175204 |  11485048 |  11801151 |
|                 Botswana |  BWA |   2120716 |   2159944 |   2205128 |   2254126 |   2303697 |
|             Burkina Faso |  BFA |  18110624 |  18646378 |  19193284 |  19751535 |  20321378 |
|               Cabo Verde |  CPV |    524743 |    531146 |    537497 |    543767 |    549935 |
|                 Cameroon |  CMR |  23298368 |  23926539 |  24566045 |  25216237 |  25876380 |
| Central African Republic |  CAF |   44

In [17]:
statdata.shape

(52, 7)

In [70]:
onlystatdata = np.delete(numdata, 0, 0)

In [71]:
print (onlystatdata)

[['39728025' '40551404' '41389198' '42228429' '43053054']
 ['27884381' '28842484' '29816748' '30809762' '31825295']
 ['10575952' '10872067' '11175204' '11485048' '11801151']
 ['2120716' '2159944' '2205128' '2254126' '2303697']
 ['18110624' '18646378' '19193284' '19751535' '20321378']
 ['524743' '531146' '537497' '543767' '549935']
 ['23298368' '23926539' '24566045' '25216237' '25876380']
 ['4493170' '4537687' '4596028' '4666377' '4745185']
 ['14110975' '14561666' '15016773' '15477751' '15946876']
 ['777424' '795592' '813892' '832322' '850886']
 ['76244544' '78789127' '81398764' '84068091' '86790567']
 ['4856095' '4980999' '5110702' '5244363' '5380508']
 ['23226143' '23822714' '24437469' '25069229' '25716544']
 ['913993' '929112' '944097' '958920' '973560']
 ['92442547' '94447072' '96442593' '98423595' '100388073']
 ['1168568' '1215179' '1262001' '1308974' '1355986']
 ['1104044' '1113984' '1124753' '1136191' '1148130']
 ['100835458' '103603501' '106400024' '109224559' '112078730']
 ['19

In [217]:
def getmean(column):
    col = onlystatdata[:, column]
    lcol = col.tolist()
    for i in range(0, len(lcol)): 
        lcol[i] = int(lcol[i])
    colmean = stats.mean(lcol)
    rcol = round (colmean, 2)
    return rcol

def getmin(column):
    col = onlystatdata[:, column]
    lcol = col.tolist()
    for i in range(0, len(lcol)): 
        lcol[i] = int(lcol[i])
    colmin = min(lcol)
    rcol = round (colmin, 2)
    return rcol

    
def getmax(column):
    col = onlystatdata[:, column]
    lcol = col.tolist()
    for i in range(0, len(lcol)): 
        lcol[i] = int(lcol[i])
    colmax = max(lcol)
    rcol = round (colmax, 2)
    return rcol

In [224]:
def getlists():
    fulldata = []
    for x in range(0,5):
        yeardata = []
        a = getmean(x)
        yeardata.append(a)
        b = getmax(x)
        yeardata.append(b)
        c = getmin(x)
        yeardata.append(c)
        fulldata.append(yeardata)
    return fulldata

In [225]:
measurearray = getlists()
measurearray = np.array(measurearray)
print (measurearray)

[[2.24916512e+07 1.81137448e+08 9.34190000e+04]
 [2.30728040e+07 1.85960289e+08 9.46770000e+04]
 [2.36644113e+07 1.90873311e+08 9.58430000e+04]
 [2.42653563e+07 1.95874740e+08 9.67620000e+04]
 [2.48746431e+07 2.00963599e+08 9.76250000e+04]]


In [226]:
a = measurearray[:, 0].tolist()
a.insert(0, 'Mean')
b = measurearray[:, 1].tolist()
b.insert(0, 'Max')
c = measurearray[:, 2].tolist()
c.insert(0, 'Min')

In [227]:
header = numdata[0, :].tolist()
header.insert(0, 'Summary Measure')
print (header)

['Summary Measure', '2015', '2016', '2017', '2018', '2019']


In [228]:
table = PrettyTable()
table.field_names = header
table.add_row(a)
table.add_row(b)
table.add_row(c)
table.align = "r"
print(table)

+-----------------+-------------+-------------+-------------+-------------+-------------+
| Summary Measure |        2015 |        2016 |        2017 |        2018 |        2019 |
+-----------------+-------------+-------------+-------------+-------------+-------------+
|            Mean | 22491651.21 | 23072804.02 | 23664411.29 | 24265356.31 | 24874643.13 |
|             Max | 181137448.0 | 185960289.0 | 190873311.0 | 195874740.0 | 200963599.0 |
|             Min |     93419.0 |     94677.0 |     95843.0 |     96762.0 |     97625.0 |
+-----------------+-------------+-------------+-------------+-------------+-------------+
